boost-test:
	@g++ test.cpp -lboost_iostreams -lboost_system -o test && ./test && rm test

drawline:
	g++ 3dline.cpp -lboost_iostreams -lboost_system  -o 3dline && ./3dline

NAME = "shubham"

hello:
	echo "My name is ${NAME}"
	
test:
	g++ test.cpp -o test && ./test && rm test

test-run:
	./test